### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by leemannd**

### CODE REVIEW

**Comment by guewen** [comment]
This file was loaded for the tests, you sure that's not required any more for the tests? Did you run them?

**Comment by leemannd** [comment]
@guewen I'running the tests and they are failing... But still, when present it triggers a pep8 error.

**Comment by guewen** [comment]
That's not a pep8 error, that's in `pylint-odoo` which does not cover this corner case. Either we fix `pylint-odoo` regarding that, either we change the test to remove the references to this data or we load the data file directly in the test.

**Comment by yvaucher** [comment]
This was inserted here:
https://github.com/leemannd/l10n-switzerland/commit/657c3d950cc52084fa67bcf3beba71b5e3496196

during portage to 9.0

We could probably just do:

```
    def _load(self, module, *args):
        tools.convert_file(self.cr, 'account_asset',
                           get_resource_path(module, *args),
                           {}, 'init', False, 'test', self.registry._assertion_report)

[...]
       self._load('account', 'test', 'account_minimal_test.xml')`
```
as done in account_asset/tests/test_account_asset.py

**Comment by leemannd** [comment]
@yvaucher I was testing this method. But still the tests are failing. I'm actually trying to correct them.

**Comment by yvaucher** [comment]
In fact we should not load this as demo data. It is loaded as test file in all official modules

**Comment by leemannd** [comment]
@yvaucher so no need to load it?

**Comment by yvaucher** [comment]
It still needed to load it as test surely depends on it, I'm just saying it should not be loaded as demo data but in tests instead.

**Comment by leemannd** [comment]
@guewen @yvaucher Tests should be running now

**Pull request merged**
